cmake_minimum_required(VERSION 3.25 FATAL_ERROR)
project(fonts-celestia-redux
        DESCRIPTION "The Celestia Redux font family, repackaged for Debian and Debian-based distros."
        VERSION 1.55.1
        HOMEPAGE_URL "http://www.mattyhex.net/CMR")
set(PROJECT_ORGANIZATION_NAME "mattyhex" CACHE STRING "" FORCE)

if(NOT UNIX)
    message(FATAL_ERROR "Must be a Linux system!")
endif()

# Celestia Medium Redux font
install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/CelestiaMediumRedux.ttf"
        DESTINATION "share/fonts/truetype")

# CPack generic setup
set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VENDOR ${PROJECT_ORGANIZATION_NAME})
set(CPACK_PACKAGE_CONTACT "mattyhex@mattyhex.net")
set(CPACK_PACKAGE_DESCRIPTION ${CMAKE_PROJECT_DESCRIPTION})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${CPACK_PACKAGE_DESCRIPTION})
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_MONOLITHIC_INSTALL ON)
set(CMAKE_INSTALL_DEFAULT_DIRECTORY_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)

# CPack deb setup
if(NOT (CPACK_GENERATOR STREQUAL "DEB"))
    message(AUTHOR_WARNING "CPack generator must be DEB! Setting generator to DEB...")
    set(CPACK_GENERATOR "DEB" CACHE INTERNAL "" FORCE)
endif()
set(CPACK_STRIP_FILES ON)
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_VENDOR} <${CPACK_PACKAGE_CONTACT}>")
set(CPACK_DEBIAN_COMPRESSION_TYPE "zstd")

include(CPack)
